name: Build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  GITHUB_REPOSITORY: raphamorim/rio
  RUST_BACKTRACE: full

jobs:
  release-macos:
    runs-on: macos-11.0
    permissions:
      contents: write
      discussions: write

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal
      - run: rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - run: make release-macos
      - name: Release version
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            release/macos-rio.zip
            LICENSE

  release-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
      discussions: write

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal
      - run: cargo build --release
      - name: Install WiX
        run: dotnet tool install --global wix --version 4.0.1
      - name: Crate msi installer
        run: |
          wix extension add WixToolset.UI.wixext WixToolset.Util.wixext
          wix build -arch "x64" -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext \
          -out "./Rio-installer.msi" "misc/windows/rio.wxs"
      - run: cp ./target/release/rio.exe ./Rio-portable.exe
      - name: Release canary
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./Rio-portable.exe
            ./Rio-installer.msi
